version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - '${DB_PORT:-5432}:${DB_PORT:-5432}'
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD='${DB_NAME:-sample}'
      - POSTGRES_USER='${DB_USER:-sample}'
      - POSTGRES_DB='${DB_PASSWORD:-sample}'