version: '3.8'
services:
  postgres:
    image: postgres:15.4-alpine
    restart: always
    ports:
      - '5432:5432'
    tty: true
    environment:
      POSTGRES_DB: '${DB_NAME:-prosklad}'
      POSTGRES_USER: '${DB_USER:-prosklad}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-prosklad}'
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass 123
    volumes:
      - cache:/data
volumes:
  redis:
    driver: local